name: CI

on: [push, pull_request]

jobs:
  build:
    name: Rust CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install rustfmt
        run: rustup component add rustfmt

      - name: Check code formatting
        working-directory: ./tapyrus-wallet-ffi
        run: cargo fmt -- --check

      - name: Run tests
        working-directory: ./tapyrus-wallet-ffi
        run: cargo test --all